#!/bin/bash
path='/root/tool/'
cd $path'AndroBugs_Framework'
git pull
cd $path'apd_launchpad'
git pull
cd $path'ARP-Poisoning-Tool'
git pull
cd $path'Bad-Pdf'
git pull
cd $path'CrackMapExec'
git pull
cd $path'datasploit'
git pull
cd $path'DeathStar'
git pull
cd $path'dnsteal'
git pull
cd $path'droopescan'
git pull
cd $path'eapeak'
git pull
cd $path'eaphammer'
git pull
cd $path'Empire'
git pull
cd $path'EyeWitness'
git pull
cd $path'gobuster'
git pull
cd $path'icebreaker'
git pull
cd $path'impacket'
git pull
cd $path'labs'
git pull
cd $path'metasploit-loader'
git pull
cd $path'Mobile-Security-Framework-MobSF'
git pull
cd $path'MyDailyScripts'
git pull
cd $path'ntlmv1-multi'
git pull
cd $path'python-pty-shells'
git pull
cd $path'Responder'
git pull
cd $path'snarf'
git pull
cd $path'subbrute'
git pull
cd $path'tcpprox'
git pull
cd $path'tomcatWarDeployer'
git pull
cd $path'vlan-hopping---frogger'
git pull
cd $path'web-shells'
git pull
cd $path'Windows-Exploit-Suggester'
git pull
cd $path'windows-privesc-check'
git pull
cd $path'winshock-test'
git pull
cd $path'xerosploit'
git pull
